### ISSUE TITLE
Query Drawer Maximize button closes query drawer

### ISSUE THREAD

**Issue by dvargas92495** [dvargas92495/roamjs-query-builder#39] opened 2023-02-06 18:08 UTC
Let's also knock out the bug surrounding refreshing results in drawer

**Comment by mdroidian** [comment] 2023-02-09 00:37
for the maximize button bug:
- the issue only happens when there is a selection
- error is undefined `mode`

https://github.com/dvargas92495/roamjs-query-builder/blob/a818f89d88937419352a5e9039a6c5544d314b34/src/components/ResultsView.tsx#L207

**Comment by mdroidian** [comment] 2023-02-09 00:38
I noticed that `Query Drawer` does not add `results` > `views` to the query tree, where `Query Block` and `Query Page` do.
It seems related, so I am looking into that as well.

**Comment by dvargas92495** [comment] 2023-02-09 02:56
ah damn yea - this views stuff was my initial idea for ORs. If you find it easier to delete stuff here by all means. It's not actually being used right now

**Comment by mdroidian** [comment] 2023-02-09 03:24
Just to be clear, this is what I was referring to.
Looks like they are used to store the `Column Views` setting.

https://user-images.githubusercontent.com/3792666/217709956-227f7b98-2d8e-42dd-9a16-bb254cac5633.mp4

**Comment by mdroidian** [comment] 2023-02-10 01:54
Yeah, that would make it so the drawer doesn't close, but then I don't think you will be able to set a column view.


https://user-images.githubusercontent.com/3792666/217980207-857426ee-1f90-44c0-baab-b789a24bed5b.mp4

**Comment by dvargas92495** [comment] 2023-02-10 15:05
Oh man this is getting gnarly - would it be solved more simply if Query Drawer passes in the views subtree as well? If not, seems like there's some other memoized state here that might not be updating in response to new views settings.

**Comment by mdroidian** [comment] 2023-02-10 22:09
Possibly.  It seems there are multiple other issues tied to this.

**RE: Refresh**
After looking into the code, if `Refresh` is meant to compare the inserted results (on a Playground page) with the current version of the saved query, then I think this actually works as intended.  Aside from #41
I assumed `Refresh` was suppose to act like it does in `Query Block` and `Query Pages`.
Maybe a UX issue?

That being said, if the `results` of the query were to change in between inserting and refreshing (via another tab or sidebar, for instance), as a user I would expect my Results View to update accordingly.  Which I don't think does.

It may also be the case that the refresh button doesn't work as intended on regular pages, but I didn't look too deeply into it, and I'm not certain that was it's intention.

**I wonder if it would be best to just patch this, close it, and re-triage the new issues?**

# New Issues
Query Drawer - Updating Settings / Initial Views on Saved Queries
Query Drawer - Add Results > Views Subtree
Query Drawer - Refresh Button, update UI/UX to represent function
Query Drawer - Refresh Button, update query
Query Drawer - Refresh Button, handle DNP `maybe`
Query Drawer - Refresh Button, fix on regular pages `maybe`

**Comment by dvargas92495** [comment] 2023-02-10 22:37
Let's make a note to discuss these New Issues on our next call before triaging

**Closed** 2023-02-10 22:39 UTC
