### ISSUE TITLE
Cannot find Creator of Graph for "Created By" Condition

### ISSUE THREAD

**Issue by mdroidian** [dvargas92495/roamjs-query-builder#12] opened 2022-10-30 21:34 UTC
I have Discourse Graph installed in two graphs.

In both I have a multiple queries finding nodes referencing multiple titles and `created by`.

And in both graphs, the creator of the graphs name doesn't show up.  
Multiple other username show up .
The name of the creator of the graph shows up when I hover over nodes he creates / edits.
His name also shows up in the `selection` of of `Author` and `Last Edited By`.

I tried manually typing in his name, but it still doesn't show up.
I also tried disabling Discourse Graph and enabling Query Builder via Roam Depot, but no luck.

Any idea what might be causing this or how I might debug it?

**Comment by dvargas92495** [comment] 2022-10-30 21:48
What does the datalog query say? On the bottom left, it should output the equivalent datalog query that you could enter in the console and start manipulating the query to see what the bug could be

**Comment by mdroidian** [comment] 2022-10-30 22:23
Ah, one thing I didn't try was fully typing in his username and trying to run the query.
I just **assumed** because it wasn't in the autocomplete that it wouldn't work.  My mistake.

If I manually type in the username and run the query, it returns the expected results. 👍

**Comment by dvargas92495** [comment] 2022-10-31 13:30
What comes up on the autocomplete?

**Comment by mdroidian** [comment] 2022-10-31 17:59
It is just blank from the UI while looking for the user (creator of the graph).

I believe it has something to do with the fact that the creator of the graph was "anonymous" for some time then changed his name to "Matt" just recently.

I tested this by creating some queries to show blocks that were created when he was "anonymous" vs when he was "Matt".  Query Builder gives an error trying to show the `selection` of `created by` when he was "anonymous".  But no error is given when querying blocks created after the change to "Matt" was made.

Blocks from `templates` were created in 2022 by "Matt"
Blocks from page `zettels` were created in 2020 by "anonymous"
Removing the selections removes the error and allows the query to run.
Third query shows "Matt" not displaying in the `created by` UI.

https://user-images.githubusercontent.com/3792666/199075090-dbdbd93d-5f9d-41b7-8f05-1a8cee137923.mp4

Below is showing the error from Chrome Console.

https://user-images.githubusercontent.com/3792666/199075278-1620a5fb-d263-4ee0-9b98-1181b9ddf93e.mp4

**Comment by dvargas92495** [comment] 2022-11-02 16:43
Ok was able to confirm these issues in the code but can't reproduce on my end - just pushed a fix for review on Roam Depot.

While it's being reviewed, we could verify the fixes from downloading the zip and loading it in developer mode from here: https://roamjs.com/extensions/query-builder

**Comment by mdroidian** [comment] 2022-11-02 18:42
Fixed!

https://user-images.githubusercontent.com/3792666/199573564-a322fad4-772a-4315-b994-ab91186dade1.mp4

**Closed** 2022-11-02 20:51 UTC
